#!/bin/zsh

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

zinit ice depth"1"; zinit light romkatv/powerlevel10k
zinit ice wait lucid; zinit light Aloxaf/fzf-tab
zinit ice depth"1"; zinit light zsh-users/zsh-autosuggestions  
# zinit ice wait lucid; zinit light zdharma-continuum/fast-syntax-highlighting  
zinit ice wait lucid; zinit light zsh-users/zsh-completions 
zinit ice wait lucid; zinit light hlissner/zsh-autopair 

zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions
 # atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
zinit ice as"program" pick"bin/git-fuzzy"
zinit light bigH/git-fuzzy
# zinit snippet OMZP::command-not-found
# command-not-found plugin
#source /etc/zsh_command_not_found
[[ -f /etc/zsh_command_not_found ]] && source /etc/zsh_command_not_found
source ~/.config/zsh/tools/aliases
source ~/.config/zsh/tools/exports
source ~/.config/zsh/tools/functions
source ~/.config/zsh/tools/evals

# Source Fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
   
# Sources # My Plugins Before zinit
# source ~/.config/zsh/plugins/syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
# source ~/.config/zsh/plugins/autosuggestions/zsh-autosuggestions.zsh
# source ~/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme
# source ~/.config/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
# source ~/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Unused Plugins
# zinit ice depth"1";zinit light zsh-users/zsh-history-substring-search  
# zinit ice depth"1";zinit light zsh-users/zsh-syntax-highlighting  
# zinit ice depth"1";zinit light ajeetdsouza/zoxide 
# zinit ice wait lucid;zinit light marlonrichert/zsh-autocomplete
# Makes Errors With Fzf Contabity with zoxide 
# zinit wait lucid for \
#  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
#     zdharma-continuum/fast-syntax-highlighting \
#  blockf \
#     zsh-users/zsh-completions \
#  atload"!_zsh_autosuggest_start" \
#     zsh-users/zsh-autosuggestions
# Old Way To Get The command not found Plugin

